# Generated by Django 3.2 on 2023-04-04 22:11

from django.db import migrations, models
import django.db.models.deletion
import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('sur_name', models.CharField(blank=True, max_length=64)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=employees.models.employees_photo_path)),
                ('job_title', models.CharField(blank=True, max_length=64)),
                ('salary', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
            ],
        ),
    ]
